REPOSITORY="sobr"
DOCKERIMAGENAME="$REPOSITORY/java8-node"
BUILD=1.0.1

docker build --rm -t $DOCKERIMAGENAME .
docker tag $DOCKERIMAGENAME $DOCKERIMAGENAME:$BUILD
docker push $DOCKERIMAGENAME:$BUILD
