REPOSITORY="katunch"
DOCKERIMAGENAME="sobr-java-node"
BUILD=1.0.0

docker build --rm --quiet -t $DOCKERIMAGENAME .
docker tag $DOCKERIMAGENAME:$BUILD $REPOSITORY/$DOCKERIMAGENAME:$BUILD
docker push $REPOSITORY/$DOCKERIMAGENAME:$BUILD
